hello:
  path: /hello/{name}
  defaults:
    name: World
#    controller: App\Controller\HelloController@sayHello
  controller: App\Controller\HelloController@sayHello

list:
  path: /
  controller: \App\Controller\TaskController@index

create:
  path: /create
  controller: \App\Controller\TaskController@create
  host: localhost
  schemes: [https, http]
  methods: [GET, POST]

show:
  path: /show/{id}
#  defaults:
#    id: 100
  controller: \App\Controller\TaskController@show
  requirements:
    id: \d+